---
# file: practice/2.application-abstractions/1.pod/pod.yaml
apiVersion: v1
kind: Pod
metadata:
  name: my-pod
  labels:
    app: my-app
spec:
  containers:
    - image: nginx:1.12
      name: nginx
      ports:
        - containerPort: 80
...
